title: Conor Haining
author: Conor Haining
email: conor.haining@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Conor Haining is a Software Engineer based in Edinburgh with an interest in mobility, learning, and healthcare.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: conorhaining.com
destination: ./build

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Conor Haining
  tagline: Software Engineer
  date_format: "%b %-d, %Y"
  style: purple
  showNav: true
  showPicker: false
  analytics_id: '116379295'

  # generate social links in footer
  social_links:
    twitter: conorhaining
    github:  ConorHaining
    linkedIn: in/conor-haining/
    email: conor.haining@gmail.com
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed
